### ISSUE TITLE
Exception: error loading class 'user_credentials'

### ISSUE THREAD

**Issue by manoelt** [filsh/yii2-oauth2-server#68]
After this commit https://github.com/Filsh/yii2-oauth2-server/commit/6d4b6be72ed4801f737949bca0597745fd0ec562 the Module is not working anymore for me.

It is throwing exception on line:

```
        foreach(array_keys($this->storageMap) as $name) {
            $storages[$name] = \Yii::$container->get($name);
        }
```

Trying to get $name = 'user_credentials' from the container.

The method `public function createStorages()` was removed from the Module class.

Stack:

``` json
{
  "name": "Exception",
  "message": "Class user_credentials does not exist",
  "code": -1,
  "type": "ReflectionException",
  "file": "/Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/di/Container.php",
  "line": 415,
  "stack-trace": [
    "#0 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/di/Container.php(415): ReflectionClass->__construct('user_credential...')",
    "#1 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/di/Container.php(358): yii\di\Container->getDependencies('user_credential...')",
    "#2 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('user_credential...', Array, Array)",
    "#3 /Users/admin/Sites/elo-jur-dico-web/vendor/filsh/yii2-oauth2-server/Module.php(100): yii\di\Container->get('user_credential...')",
    "#4 /Users/admin/Sites/elo-jur-dico-web/vendor/filsh/yii2-oauth2-server/filters/auth/CompositeAuth.php(14): filsh\yii2\oauth2server\Module->getServer()",
    "#5 /Users/admin/Sites/elo-jur-dico-web/common/classes/CompositeAuth.php(15): filsh\yii2\oauth2server\filters\auth\CompositeAuth->beforeAction(Object(yii\base\InlineAction))",
    "#6 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/ActionFilter.php(70): common\classes\CompositeAuth->beforeAction(Object(yii\base\InlineAction))",
    "#7 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))",
    "#8 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))",
    "#9 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/Controller.php(269): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))",
    "#10 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/web/Controller.php(121): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))",
    "#11 /Users/admin/Sites/elo-jur-dico-web/frontend/controllers/api/v1/EloRestController.php(44): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))",
    "#12 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/Controller.php(152): frontend\controllers\api\v1\EloRestController->beforeAction(Object(yii\base\InlineAction))",
    "#13 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('escritorio', Array)",
    "#14 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('api/v1/escritor...', Array)",
    "#15 /Users/admin/Sites/elo-jur-dico-web/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))",
    "#16 /Users/admin/Sites/elo-jur-dico-web/frontend/web/index.php(18): yii\base\Application->run()",
    "#17 {main}"
  ]
}
```

Config:

``` php
'modules' => [
        'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
           'tokenParamName' => 'accessToken',
           'tokenAccessLifetime' => 3600 * 24,
            'storageMap' => [
                'user_credentials' => 'common\models\UserOAuth'
            ],
            'grantTypes' => [
                'client_credentials' => [
                    'class' => 'OAuth2\GrantType\ClientCredentials',
                    'allow_public_clients' => false
                ],
                'user_credentials' => [
                    'class' => 'OAuth2\GrantType\UserCredentials'
                ],
                'refresh_token' => [
                    'class' => 'OAuth2\GrantType\RefreshToken',
                    'always_issue_new_refresh_token' => true
                ]
            ]
        ]
    ],
```

**Comment by mtangoo** [comment]
Can anyone else test this. So far mine works fine.  Can you tra to set jwt option to false explicitly (see read me how to do it) am not on PC but am wondering what's the issue

**Comment by mtangoo** [comment]
So I went through the code comparing and found strange thing
1. master is far outdated than 2.0.1(controller name is still Default)
2. I found that I forked 2.0.1 which is the latest and applied PR against master

Am not sure what happened, but that is the case. @Filsh can help on that may be but meanwhile am going to send PR changes to 2.0.1 branch

**Comment by mtangoo** [comment]
So my findings are:
1. master branch is quiet different from 2.0.1 The 2.0.1 have Bootstrap file that lists dependencies to be injected but master does not have.
2. I created PR using 2.0.1 branch and sent it to master. My suggestions are @Filsh reverts the merging of my two PR against master and I will create another one against 2.0.1

@Filsh what's the difference between 2.0.1 branch vs master?

**Comment by mtangoo** [comment]
See https://github.com/Filsh/yii2-oauth2-server/pull/69

**Comment by mrak1990** [comment]
bump

**Comment by mtangoo** [comment]
@mrak1990  did you see my note?If not here it is
>See #69

**Comment by SuhoverhovSergey** [comment]
I have same problem with user_credentials class.

**Comment by mtangoo** [comment]
See #60

**Comment by varp** [comment]
Fixed
